[package]
name = "omake"
version = "0.1.0"
edition = "2021"
description = "A Rust implementation of make."
authors = ["Gregory N. Schmit <schmitgreg@gmail.com>"]
license = "MIT"
repository = "https://github.com/gregschmit/make"

[dependencies]
clap = { version = ">= 3.2.17", features = ["derive"] }
const_format = { version = ">= 0.2.26" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
